[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
'''

# open terminal
[[plugins]]
repo = 'Shougo/deol.nvim'

# for denite.vim
[[plugins]]
repo = 'Shougo/neomru.vim'

# TOML
[[plugins]]
repo = 'cespare/vim-toml'

# Syntax Highlighting Tool
[[plugins]]
repo = 'sheerun/vim-polyglot'

# Vim emoji
[[plugins]]
repo = 'junegunn/vim-emoji'

# PostFix ext
[[plugins]]
repo = 'mattn/vim-sonictemplate'

# Vim LSP
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

# PowerShell
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ['ps1', 'psm']

# LSP by TabNine
[[plugins]]
repo = 'neoclide/coc-tabnine'

[[plugins]]
repo = 'vim-denops/denops.vim'

# ddc.vim - 補完
[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['vim-denops/denops.vim']
hook_source = '''
call ddc#custom#patch_global('completionMenu', 'pum.vim')
call ddc#custom#patch_global('sources', [
 \ 'around',
 \ 'vim-lsp',
 \ 'file'
 \ ])
call ddc#custom#patch_global('sourceOptions', {
 \ '_': {
 \   'matchers': ['matcher_head'],
 \   'sorters': ['sorter_rank'],
 \   'converters': ['converter_remove_overlap'],
 \ },
 \ 'around': {'mark': 'Around'},
 \ 'vim-lsp': {
 \   'mark': 'LSP',
 \   'matchers': ['matcher_head'],
 \   'forceCompletionPattern': '\.|:|->|"\w+/*'
 \ },
 \ 'file': {
 \   'mark': 'file',
 \   'isVolatile': v:true,
 \   'forceCompletionPattern': '\S/\S*'
 \ }})
call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'LumaKernel/ddc-file'

# Deno-powered filer
# [[plugins]]
# repo = 'Shougo/ddu.vim'
