[[plugins]]
repo = 'python-mode/python-mode'
on_ft = 'python'

[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

# PowerShell
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ['ps1', 'psm']

# LSP by TabNine
[[plugins]]
repo = 'neoclide/coc-tabnine'

# LSP for PowerShell
#[[plugins]]
#repo = 'corbob/vim-powershell'
#depends = 'autozimu/LanguageClient-neovim'
#build = 'pwsh build.ps1'
#rev = 'dev'
#if = 'v:false'
