[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

# PowerShell
[[plugins]]
repo = 'PProvost/vim-ps1'
on_ft = ['ps1', 'psm']

# LSP by TabNine
[[plugins]]
repo = 'neoclide/coc-tabnine'
