# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"

apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = ""

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-syntax-highlighting-filetypes]
github = "trapd00r/zsh-syntax-highlighting-filetypes"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# mask secret for history
[plugins.passwordless-history]
github = "jgogstad/passwordless-history"

[plugins.asdf]
github = "asdf-vm/asdf"

[plugins.zsh-better-npm-completion]
github = "lukechilds/zsh-better-npm-completion"

