# Don't print a new line at the start of the prompt
add_newline = true

[aws]
symbol = "\uF270 "

[character]
symbol = "\u2771 "
error_symbol = "\u2A2F "
use_symbol_for_status = true

[golang]
symbol = "\uE527 "

[git_status]
conflicted = "\u26A0 "
renamed = "\u270E "
prefix = ""
suffix = " "
style = "bold magenta"

[git_branch]
symbol = "\uE709 "

[jobs]
symbol = "\u271C"

[java]
symbol = "\uE638 "

[nodejs]
symbol = "\uE69B "

[package]
#symbol = "\uF5F3 "

[python]
symbol = "\uE63C "

[ruby]
symbol = "\uE639 "

[rust]
symbol = "\uE6A8 "

[time]
disabled = false
format = "%T"

[battery]
full_symbol = "🔋"
charging_symbol = "⚡"
discharging_symbol = "💨"
