# Don't print a new line at the start of the prompt
add_newline = true

[aws]
symbol = "\uF270"

[golang]
symbol = "\uE626"

[git_status]
conflicted = "🚨 "
renamed = "🆕 "
prefix = ""
suffix = " "
style = "bold magenta"

[git_branch]
symbol = "\uF113 "

[python]
symbol = "\uE73C "

[time]
disabled = false
format = "\uF017 %T"

[battery]
full_symbol = "🔋"
charging_symbol = "⚡"
discharging_symbol = "💨"
