# Don't print a new line at the start of the prompt
add_newline = true

[aws]
symbol = "\uF270 "

[character]
symbol = "\u300B "
error_symbol = "\u2A2F "
use_symbol_for_status = true

[golang]
symbol = "\uE527 "

[git_status]
conflicted = "\u26A0 "
renamed = "\u270E "
prefix = "at:"
suffix = " "
style = "magenta"

[git_branch]
symbol = "\uF407 "

[jobs]
symbol = "\u271C"

[java]
symbol = "\uE738 "
style = "red"

[nodejs]
symbol = "\uE718 "

[package]
symbol = "\uF06B "

[python]
symbol = "\uE73C "

[ruby]
symbol = "\uE739 "

[rust]
symbol = "\uE6A8 "

[time]
disabled = false
format = "%T"

[battery]
full_symbol = "🔋"
charging_symbol = "⚡"
discharging_symbol = "💨"
