# Additional git repositories to pull
git_repos = [
    "~/Dotfiles",
    "~/.zprezto",
    "~/.goenv",
    "~/.rbenv",
    "~/pigweed",
    "~/.themes/elementary-x"
]

# Don't pull the predefined git repos
# predefined_git_repos = false

# Disable specific steps - same options as the command line flag
disable = ["vim",]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
#no_retry = true

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
ssh_arguments = "-o ConnectTimeout=2"

# Arguments to pass Git when pulling Repositories
git_arguments = "--rebase --autostash"

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Arguments to pass yay when updating packages
#yay_arguments = "--nodevel"

# Manually select Windows updates
# accept_all_windows_updates = false

# Cleanup temporary or old files
cleanup = true

# Do not set the terminal title
#set_title = false
# Commands to run before anything
[pre_commands]
#"NeoVim Snapshot" = "rm -rf ~/.local/bin/nvim.bak && cp -rl ~/.local/bin/nvim ~/.local/bin/nvim.bak"
#"Update NodeJS by N" = "n lts; npm --version"
"Update pip" = "python -m pip install -U --upgrade-strategy eager pip"
"pyenv" = "pyenv update; exit 0"
"anyenv" = "anyenv update; exit 0"

# Custom commands
[commands]
"Python Core Packages" = "python -m pip install -U --upgrade-strategy eager pipenv poetry hatch setuptools certifi"
"Python envs" = "pipenv update --dev --clear; pipenv install --dev --system"
"NPM" = "npm install npm -g; npm update; npm doctor; npm dedupe; npm audit fix"
