# Additional git repositories to pull
git_repos = [
    "~/Dotfiles",
    "~/.zprezto",
    "~/.goenv",
    "~/.rbenv"
]

# Don't pull the predefined git repos
# predefined_git_repos = false

# Disable specific steps - same options as the command line flag
#disable = ["system", "emacs"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
#no_retry = true

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
ssh_arguments = "-o ConnectTimeout=2"

# Arguments to pass Git when pulling Repositories
git_arguments = "--rebase --autostash"

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Arguments to pass yay when updating packages
#yay_arguments = "--nodevel"

# Manually select Windows updates
# accept_all_windows_updates = false

# Cleanup temporary or old files
cleanup = true

# Do not set the terminal title
#set_title = false
# Commands to run before anything
[pre_commands]
"NeoVim Snapshot" = "rm -rf ~/.local/bin/nvim.bak && cp -rl ~/.local/bin/nvim ~/.local/bin/nvim.bak"
"Update NodeJS by N" = "n lts; npm --version"

# Custom commands
[commands]
"Update pip" = "python -m pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager pip"
"Python envs" = "pipenv update --dev --clear; pipenv install --dev --system"
"NPM" = "npm install npm -g; npm update; npm doctor; npm dedupe; npm audit fix"
