[misc]
# Disable specific steps - same options as the command line flag
disable = ["gnome_shell_extensions", "asdf", "containers", "uv"]

# Arguments to pass SSH when upgrading remote systems
ssh_arguments = "-o ConnectTimeout=2"

# Cleanup temporary or old files
cleanup = true

# Commands to run before anything
[pre_commands]

# Commands to run after anything
[post_commands]

# Custom commands
[commands]
#"10. Update pip" = "python -m pip install -U --upgrade-strategy eager pip"
#"20. Python Core Packages" = "python3 -m pip install --upgrade setuptools"
#"40. Vim/Neovim Libraries in Python" = "python3 -m pip install --upgrade neovim vim-vint"
#"Python envs" = "poetry update"
"10. NodeJS by Volta" = "volta install node" # install node@lts
"20. NPM globally" = "npm install -g npm"
"20. PNPM globally" = "pnpm install -g pnpm"
#"30. Check nodejs pkgs" = "npm doctor; npm audit fix"
"30. Check NodeJS Packages via PNPM" = "pnpm doctor; pnpm audit fix"


[brew]
# For the BrewFormula step
# Execute `brew autoremove` after the step.
autoremove = true

[git]
# Additional git repositories to pull
repos = [
    "~/Dotfiles",
]


